# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6809e4a39b1fe04eb8d5cacfefd2c78a2decad3e979d192b7bbb1f137796369a202e5b85bce90ab110c25b937f0dac2b96d9d0a2e9c5f6dd49865a6b5bd68b77

test:
  secret_key_base: aa5db9fabf47b2c57e637026c2dc9988e3825c29db1a6d541dd7cfc695da5b7bb7ca88d656fbd190cda6b2e604d9d84a56b5da466be901a0a6f5f27729940627

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
